# Config for geodesic codebook construction (Fashion-MNIST) with K=1024
# Based on CIFAR-10 findings: use mu.pt, k=50, union symmetry

data:
  latents_path: experiments/vae_fashion/latents_train/mu.pt

out:
  dir: experiments/geo/codebook_fashion_k1024_mu_k50

graph:
  k: 50
  metric: euclidean
  sym: union
  mode: distance

quantize:
  K: 1024
  init: kpp
  seed: 42

system:
  device: auto
