# CIFAR-10 Vanilla VAE Geodesic Sample Generation Config
# Organized structure: experiments/cifar10/vanilla/geodesic/evaluation/

# Model checkpoints and paths
transformer_ckpt_path: "experiments/cifar10/vanilla/geodesic/transformer/checkpoints/best.pt"
vae_ckpt_path: "experiments/cifar10/vanilla/geodesic/vae/checkpoints/best.pt"
codebook_path: "experiments/cifar10/vanilla/geodesic/codebook/codebook.pt"

# Model configurations (must match training config)
transformer:
  num_tokens: 513  # 512 codes + 1 BOS token
  embed_dim: 512   # Restored original capacity
  n_layers: 8      # Restored original depth
  n_head: 8        # Restored original heads
  max_seq_len: 2   # [BOS, code]
  num_classes: 10
  dropout: 0.2     # Moderate increase

vae:
  latent_dim: 128
  in_channels: 3
  enc_channels: [64, 128, 256]
  dec_channels: [256, 128, 64]
  norm_type: "batch"

# Balanced generation parameters
num_samples: 100  # 10 samples per class
temperature: 1.1  # Slightly higher for diversity
top_k: 40         # Balanced sampling
class_labels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # All CIFAR-10 classes
samples_per_class: 10

# Output settings
output_dir: "experiments/cifar10/vanilla/geodesic/evaluation"
output_filename: "generated_samples.png"

# System settings
device: "cuda"
seed: 42
vanilla_vae: true

