# CIFAR-10 Vanilla VAE Training Config (Geodesic Pipeline)
# Organized structure: experiments/cifar10/vanilla/geodesic/vae/

seed: 42
device: auto
max_epochs: 200
lr: 3e-4
weight_decay: 1e-4
log_interval: 100
val_interval: 1
early_stop: 20
kl_anneal_epochs: 50
optimizer: adamw
scheduler:
  name: cosine
  t_max: 200
grad_clip_max_norm: 1.0
beta: 1.0

# Output directory following new structure
out_dir: experiments/cifar10/vanilla/geodesic/vae
save_latents: true
mlflow_tracking_uri: experiments/mlruns
experiment_name: CIFAR10_Vanilla_VAE_Geodesic
run_name: vanilla_vae_geodesic

# Data configuration
data:
  root: ./data
  name: CIFAR10
  batch_size: 256
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  augment: true

# Vanilla VAE Model configuration
model:
  in_channels: 3
  output_image_size: 32
  latent_dim: 128
  enc_channels: [64, 128, 256]
  dec_channels: [256, 128, 64]
  recon_loss: mse
  norm_type: batch
  mse_use_sigmoid: false
  free_bits_default: 0.25
  capacity_max_default: 25.0
  capacity_anneal_steps_default: 100000
  capacity_mode_default: abs

