# Config for build codebook geodesic (CIFAR-10)
data:
  latents_path: experiments/vae_cifar10/latents_train/mu.pt

out:
  dir: experiments/geo/codebook_cifar10_k512_kNN10

graph:
  k: 48
  metric: euclidean   # or cosine
  sym: union
  mode: connectivity

quantize:
  K: 512
  init: kpp
  seed: 42

system:
  device: cpu
