# Configuration for sampling from the trained Transformer on CIFAR-10

transformer_ckpt_path: experiments/transformer_cifar10_geodesic_k512_cond_ls_mu/checkpoints/best.pt
vae_ckpt_path: experiments/spatial_vae_cifar10/checkpoints/best.pt
codebook_path: experiments/spatial_codebook_cifar10_geodesic_k512_mu/codebook.pt
out_path: "qualitative_results/cifar10_geodesic_k512_cond_ls_mu.png"

transformer:
  num_classes: 10
  num_tokens: 512
  embed_dim: 256
  n_layers: 4
  n_head: 4
  max_seq_len: 16
  dropout: 0.1

vae:
  in_channels: 3
  output_image_size: 32
  latent_dim: 32
  enc_channels: [64, 128, 256]
  dec_channels: [256, 128, 64]
  recon_loss: "mse"
  norm_type: "batch"
  mse_use_sigmoid: false

sampling:
  samples_per_class: 8
  temperature: 1.0
  top_k: 100
  class_labels: [0, 1, 3] # airplane, automobile, cat
