seed: 42
device: auto
max_epochs: 20
lr: 3e-4
weight_decay: 1e-4
log_interval: 100
val_interval: 1
early_stop: 0
kl_anneal_epochs: 10
out_dir: ./experiments/vae
save_latents: true
mlflow_tracking_uri: ./experiments/mlruns
experiment_name: VAE_MNIST
run_name: vae_mnist_latent128_beta1.0

optimizer: adamw
scheduler:
  name: cosine
  t_max: 20

grad_clip_max_norm: 1.0


