# VAE architecture for MNIST
in_channels: 1
output_image_size: 28
latent_dim: 128
enc_channels: [64, 128, 256]
dec_channels: [256, 128, 64]
recon_loss: bce
beta: 1.0
norm_type: batch
mse_use_sigmoid: true


