# Config di base per VQ-VAE su CIFAR-10
seed: 42
data:
  root: ./data
  num_workers: 4
  img_size: 32
  normalize_mean: [0.5, 0.5, 0.5]
  normalize_std:  [0.5, 0.5, 0.5]
train:
  batch_size: 128
  epochs: 100
  lr: 0.0002
  weight_decay: 0.0
  grad_clip: 1.0
  amp: true
model:
  in_channels: 3
  z_channels: 128
  hidden: 256
  n_res_blocks: 2
  n_codes: 512
  beta: 0.25           # commitment
  ema_decay: 0.99      # EMA codebook decay (0.99–0.999)
  ema_eps: 1.0e-5
log:
  samples_every: 1     # salva ricostruzioni ogni N epoche
  save_best: true
