# Fashion-MNIST geodesic vs Euclidean comparison (K=1024, k=50)

data:
  latents_path: "experiments/vae_fashion/latents_val/z.pt"
  checkpoint_path: "experiments/vae_fashion/checkpoints/best.pt"

quantization:
  K: 1024
  seed: 42

graph:
  k: 50
  metric: "euclidean"
  sym: "union"
  mode: "distance"

experiment:
  device: "auto"
  save_plots: true
  save_metrics: true

output:
  base_dir: "demo_outputs/codebook_comparison_fashion_k1024"
  timestamp: true
  save_codebook: false

