# Memory Efficient configuration for codebook comparison demo
# Small codebook with low connectivity for fast testing

# Data paths
data:
  latents_path: "experiments/vae_mnist/latents_val/z.pt"
  checkpoint_path: "experiments/vae_mnist/checkpoints/best.pt"

# Quantization parameters
quantization:
  K: 32                    
  seed: 42                 
  
# Graph construction
graph:
  k: 8                    
  metric: "euclidean"     
  sym: "mutual"           
  mode: "distance"         

# Experimental settings
experiment:
  device: "auto"           
  save_plots: true         
  save_metrics: true       
  
# Output configuration
output:
  base_dir: "demo_outputs/codebook_comparison_memory_efficient"
  timestamp: true          
  save_codebook: false     
