# Configuration for codebook comparison demo
# Geodesic vs Euclidean quantization comparison

# Data paths
data:
  latents_path: "experiments/vae_mnist/latents_val/z.pt"
  checkpoint_path: "experiments/vae_mnist/checkpoints/best.pt"

# Quantization parameters
quantization:
  K: 64                    # Number of codebook entries
  seed: 42                 # Random seed for reproducibility
  
# Graph construction for geodesic method
graph:
  k: 10                    # k-NN connectivity parameter
  metric: "euclidean"      # Distance metric for k-NN (euclidean, cosine)
  sym: "mutual"            # Graph symmetry (mutual, union)
  mode: "distance"         # Edge weight mode

# Experimental settings
experiment:
  device: "auto"           # Device selection (auto, cuda, cpu)
  save_plots: true         # Generate comparison visualizations
  save_metrics: true       # Save detailed metrics to JSON
  
# Output configuration
output:
  base_dir: "demo_outputs/codebook_comparison_test1"
  timestamp: true          # Add timestamp to output directory
  save_codebook: false     # Save individual codebooks (large files)
