# High Resolution configuration for codebook comparison demo
# Large codebook with high connectivity for maximum quality

# Data paths
data:
  latents_path: "experiments/vae_mnist/latents_val/z.pt"
  checkpoint_path: "experiments/vae_mnist/checkpoints/best.pt"

# Quantization parameters
quantization:
  K: 256                  
  seed: 42                 
  
# Graph construction
graph:
  k: 30                    
  metric: "cosine"         
  sym: "union"            
  mode: "distance"         

# Experimental settings
experiment:
  device: "auto"           
  save_plots: true         
  save_metrics: true       
  
# Output configuration
output:
  base_dir: "demo_outputs/codebook_comparison_high_res"
  timestamp: true          
  save_codebook: false     
