# Standard configuration for codebook comparison demo
# Geodesic vs Euclidean quantization comparison

# Data paths
data:
  latents_path: "experiments/vae_mnist/latents_val/z.pt"
  checkpoint_path: "experiments/vae_mnist/checkpoints/best.pt"

# Quantization parameters
quantization:
  K: 64                    
  seed: 42                 
  
# Graph construction for geodesic method
graph:
  k: 10                    
  metric: "euclidean"      
  sym: "mutual"            
  mode: "distance"         

# Experimental settings
experiment:
  device: "auto"           
  save_plots: true         
  save_metrics: true       
  
# Output configuration
output:
  base_dir: "demo_outputs/codebook_comparison_test1"
  timestamp: true          
  save_codebook: false     
