# Multi-Metric configuration for codebook comparison demo
# Statistical robustness with multiple seeds and comprehensive analysis

# Data paths
data:
  latents_path: "experiments/vae_mnist/latents_val/z.pt"
  checkpoint_path: "experiments/vae_mnist/checkpoints/best.pt"

# Quantization parameters
quantization:
  K: 128                  
  seed: 42                 
  
# Graph construction
graph:
  k: 15                    
  metric: "euclidean"     
  sym: "union"            
  mode: "distance"         

# Experimental settings
experiment:
  device: "auto"           
  save_plots: true         
  save_metrics: true       
  
# Output configuration
output:
  base_dir: "demo_outputs/codebook_comparison_multi_metric"
  timestamp: true          
  save_codebook: true      
