# Configuration for sampling from the trained Transformer

transformer_ckpt_path: experiments/transformer_fashion_geodesic_k512_conditional_200epochs/checkpoints/best.pt
vae_ckpt_path: experiments/spatial_vae_fashionmnist/checkpoints/best.pt
codebook_path: experiments/spatial_codebook_fashion_geodesic_k512/codebook.pt
out_path: "qualitative_results/fashion_geodesic_k512_conditional_multiclass_200epochs.png"

transformer:
  num_classes: 10
  num_tokens: 512
  embed_dim: 256
  n_layers: 4
  n_head: 4
  max_seq_len: 16
  dropout: 0.1

vae:
  in_channels: 1
  output_image_size: 28
  latent_dim: 16
  enc_channels: [64, 128, 256]
  dec_channels: [256, 128, 64]
  recon_loss: "mse"
  norm_type: "batch"

sampling:
  samples_per_class: 8
  temperature: 1.0
  top_k: 50
  class_labels: [0, 1, 9] # 0=T-shirt, 1=Jeans, 9=Shoes
