# Dataset & DataLoader for Fashion-MNIST
# name: one of [MNIST, FashionMNIST, CIFAR10]
root: ./data
name: FashionMNIST
batch_size: 256
num_workers: 16
pin_memory: true
persistent_workers: true
augment: true
