# Sandbox config for benchmark (MNIST)
data:
  latents_path: experiments/vae_mnist/latents_train/z.pt
  labels_path: experiments/vae_mnist/latents_train/y.pt

out:
  dir: experiments/geo/codebook_benchmark_k128_kNN10

graph:
  k: 10
  metric: euclidean
  sym: mutual
  mode: distance

quantize:
  K: 128
  init: kpp
  seed: 42

system:
  device: cpu

test:
  subset_size: 10000
