# Config for build codebook geodesic (CIFAR-10)
data:
  latents_path: experiments/vae_cifar10/latents_train/z.pt

out:
  dir: experiments/geo/codebook_cifar10_k512_kNN10

graph:
  k: 100
  metric: euclidean
  sym: mutual
  mode: distance

quantize:
  K: 512
  init: kpp
  seed: 42

system:
  device: cpu
