seed: 42
device: auto
max_epochs: 100  
lr: 3e-4
weight_decay: 0.0
log_interval: 100
val_interval: 1
early_stop: 0
kl_anneal_epochs: 50
out_dir: ./experiments/vae
save_latents: true
mlflow_tracking_uri: ./experiments/mlruns
experiment_name: VAE_CIFAR10
run_name: vae_latent128_beta1.0_anneal50