data:
  checkpoint_path: experiments/vae_cifar10/checkpoints/best.pt
  latents_path: experiments/vae_cifar10/latents_train/z.pt
experiment:
  device: auto
  save_metrics: true
  save_plots: true
graph:
  k: 20
  metric: euclidean
  mode: distance
  sym: mutual
output:
  base_dir: demo_outputs/codebook_comparison_cifar10
  timestamp: true
quantization:
  K: 512
  seed: 42
